### ISSUE TITLE
[question] info

### ISSUE THREAD

**Issue by xenogenesi** [danilw/Krita-StableDiffusion-WebUI-Colab#1]
Cool, thanks for sharing this!

Do you plan to also support https://github.com/Interpause/auto-sd-paint-ext with Colab?

Do the new models also work without modifications? Just add the url? Has anyone tried them? (v1-5-pruned-emaonly.ckpt, sd-v1-5-inpainting.ckpt)

Regarding plugin-server encrypted communications, ngrok creates both http and https (same url) and https seems to work with the Krita plugin without modification. The patches mentioned in the readme for encryption are still necessary for privacy on the server (if the images are saved as a file on the server and if the prompts are saved in some log / cli history, or saved in some file associated with the images)

A change I made that maybe it can be useful to someone, to use the model from google drive:

```diff
## modified /cells/12/source:
@@ -1,8 +1,14 @@
 #@title Model
-user_header = f"\"Authorization: Bearer {huggingface_user_token}\""
-tflname = "/content/stable-diffusion-webui/"+local_file_name
+from google.colab import drive
+drive_path = "/content/drive"
+drive.mount(drive_path,force_remount=True)
+#/content/drive/MyDrive/AI/models/sd-v1-4.ckpt
+tflname = "/content/drive/MyDrive/AI/models/sd-v1-4.ckpt"
 if(not os.path.exists(tflname)):
-  !wget --header={user_header} $local_model_url
+  user_header = f"\"Authorization: Bearer {huggingface_user_token}\""
+  tflname = "/content/stable-diffusion-webui/"+local_file_name
+  if(not os.path.exists(tflname)):
+    !wget --header={user_header} $local_model_url
 if(os.path.exists("/content/stable-diffusion-webui/model.ckpt")):
   !rm "/content/stable-diffusion-webui/model.ckpt"
 !ln -s "$tflname" "/content/stable-diffusion-webui/model.ckpt"
```

It could probably be better added as an option.
In this way the download is not carried out every time the instance is restarted, the loading of the model, however, is a little slower when the service is started (and obviously takes up space in google drive)

**Comment by danilw** [comment]
> Do you plan to also support https://github.com/Interpause/auto-sd-paint-ext with Colab?

yes, tomorrow maybe, I was waiting when there be Encryption support, look like it added now

> Do the new models also work without modifications? Just add the url? Has anyone tried them? (v1-5-pruned-emaonly.ckpt, sd-v1-5-inpainting.ckpt)

if models works in default StableDiffusion - they will work same way here, links in this script is just "user friendly text" that easy can be changed

> Regarding plugin-server encrypted communications, ngrok creates both http and https

client side of this plugin support only http link

**About your change - I point this moment:**
> tflname = "/content/drive/MyDrive/AI/models/sd-v1-4.ckpt"

**speed of "your mounted google drive at server" is about 10 Mb/sec** (at best, usually much less) and when you mounted it - it "does not instantly move all data to the server", it doing it "slowly in bacgkround

when speed of cached file(model) from internet (that downloaded very often) in Google Colab VM is about 100 Mb/sec (min I have seen) to 400 Mb/sec 

So - downloading "from internet" is many times faster than using your Colab.

> In this way the download is not carried out every time the instance is restarted

I literally tested it, I had similar idea, but it about 10-20 times slower to just download gigabytes from Google Drive than from internet (remember **static files from internet can be cached by google so it "not from internet", when your google drive - never cached because only you downloading it**)

**Comment by danilw** [comment]
il close this issue when il add new script for auto-sd-paint-ext 

if you have more questions/want share/learn some info - we can do it using real time communication in my discord, join link on page

**Comment by danilw** [comment]
Update - I wont update anything now, it works so I keep it as it is. People who still use this plugin can make changes they need.

Better way is just make new Colab for new plugin https://github.com/Interpause/auto-sd-paint-ext that I wont do for now.

So I close it.
